<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/src/admin.proto

namespace Admin\UnlockEventAwardsRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>admin.UnlockEventAwardsRequest.Member</code>
 */
class Member extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account = 1;</code>
     */
    protected $account = '';
    /**
     * Generated from protobuf field <code>string vip_level = 2;</code>
     */
    protected $vip_level = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account
     *     @type string $vip_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Grpc\Src\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account = 1;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>string account = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string vip_level = 2;</code>
     * @return string
     */
    public function getVipLevel()
    {
        return $this->vip_level;
    }

    /**
     * Generated from protobuf field <code>string vip_level = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVipLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->vip_level = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Member::class, \Admin\UnlockEventAwardsRequest_Member::class);

