<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/src/admin.proto

namespace GPBMetadata\Src\Grpc\Src;

class Admin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
D
src/grpc/src/admin.protoadmin2
AdminServiceB	Z./adminbproto3'
        , true);

        static::$is_initialized = true;
    }
}

