<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/src/game.proto

namespace GPBMetadata\Src\Grpc\Src;

class Game
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ê
src/grpc/src/game.protogame"\\
MemberBalanceRequest
opCode (	
account (	
gameBrandCode (	
lang (	"_
MemberBalanceResponse
account (	

walletCode (	
balance (
currency (	"[
CreateMemberRequest
opCode (	
account (	
gameBrandCode (	
lang (	"\'
CreateMemberResponse
account (	"k
LaunchGameRequest
opCode (	
account (	
gameBrandCode (	
gameCode (	
lang (	"!
LaunchGameResponse
url (	"z
TransferInRequest
opCode (	
account (	
gameBrandCode (	
lang (	
traceId (	
amount ("k
TransferOutRequest
opCode (	
account (	
gameBrandCode (	
lang (	
traceId (	"T
TransferResponse
opCode (	
account (	
amount (
traceId (	"t
GetPlayerTransactionRequest
opCode (	
account (	
gameBrandCode (	
lang (	
traceId (	"x
GetPlayerTransactionResponse
account (	
beforeBalance (
amount (
balance (
traceId (	"‚
GetAllGamesRequest
opCode (	
account (	
lang (	
vendor (	
filter (	
page (
perPage ("}
GetAllGamesResponse
currentPage (
perPage (
lastPage (
total (
data (2.game.AllGameData"Ô
AllGameData
gameCode (	
hot (	
localizedName (	
localizedRemark (	
new (	
playerCount (	
status (	
featured (	
favor	 (	#
game
 (2.game.AllGameDataGame"I
AllGameDataGame
gameBrandCode (	
gameCode (	
image (	"„
GetFavorGamesRequest
opCode (	
account (	
lang (	
vendor (	
filter (	
page (
perPage ("
GetFavorGamesResponse
currentPage (
perPage (
lastPage (
total (
data (2.game.AllGameData"3
HZVerifySessionTokenRequest
sessionToken (	"S
HZVerifySessionTokenResponse
opCode (	
account (	

memberCode (	"G
GetBetlogDetailRequest
opCode (	
traceId (	
lang (	"&
GetBetlogDetailResponse
url (	2÷
GameK
getMemberBalance.game.MemberBalanceRequest.game.MemberBalanceResponseE
createMember.game.CreateMemberRequest.game.CreateMemberResponse?

launchGame.game.LaunchGameRequest.game.LaunchGameResponse=

transferIn.game.TransferInRequest.game.TransferResponse?
transferOut.game.TransferOutRequest.game.TransferResponse]
getPlayerTransaction!.game.GetPlayerTransactionRequest".game.GetPlayerTransactionResponseN
getBetlogDetail.game.GetBetlogDetailRequest.game.GetBetlogDetailResponseB
getAllGames.game.GetAllGamesRequest.game.GetAllGamesResponseH
getFavorGames.game.GetFavorGamesRequest.game.GetFavorGamesResponse]
hzVerifySessionToken!.game.HZVerifySessionTokenRequest".game.HZVerifySessionTokenResponseBZ./gameÊGrpc\\Build\\Gamebproto3'
        , true);

        static::$is_initialized = true;
    }
}

