<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc/src/transaction.proto

namespace Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transaction.MemberWallet</code>
 */
class MemberWallet extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account = 1;</code>
     */
    protected $account = '';
    /**
     * Generated from protobuf field <code>string walletCode = 2;</code>
     */
    protected $walletCode = '';
    /**
     * Generated from protobuf field <code>double balance = 3;</code>
     */
    protected $balance = 0.0;
    /**
     * Generated from protobuf field <code>string isClose = 4;</code>
     */
    protected $isClose = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account
     *     @type string $walletCode
     *     @type float $balance
     *     @type string $isClose
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Src\Grpc\Src\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account = 1;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>string account = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string walletCode = 2;</code>
     * @return string
     */
    public function getWalletCode()
    {
        return $this->walletCode;
    }

    /**
     * Generated from protobuf field <code>string walletCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWalletCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->walletCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double balance = 3;</code>
     * @return float
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Generated from protobuf field <code>double balance = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkDouble($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string isClose = 4;</code>
     * @return string
     */
    public function getIsClose()
    {
        return $this->isClose;
    }

    /**
     * Generated from protobuf field <code>string isClose = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIsClose($var)
    {
        GPBUtil::checkString($var, True);
        $this->isClose = $var;

        return $this;
    }

}

